import { create } from "zustand";
import { devtools } from "zustand/middleware";

interface AIGeneratorState {
  // Input parameters
  theme: string;
  setting: string;
  characters: string;
  conflict: string;
  tone: string;
  length: string;

  // Generation state
  isGenerating: boolean;
  generatedStory: string;
  generationStep: number;
  generationProgress: number;

  // UI state
  selectedPreset: string | null;
  showAdvanced: boolean;

  // Actions
  setTheme: (theme: string) => void;
  setSetting: (setting: string) => void;
  setCharacters: (characters: string) => void;
  setConflict: (conflict: string) => void;
  setTone: (tone: string) => void;
  setLength: (length: string) => void;
  setGenerating: (generating: boolean) => void;
  setGeneratedStory: (story: string) => void;
  setGenerationStep: (step: number) => void;
  setGenerationProgress: (progress: number) => void;
  setSelectedPreset: (preset: string | null) => void;
  setShowAdvanced: (show: boolean) => void;
  resetForm: () => void;
  generateStory: () => Promise<void>;
}

const mockStoryTemplates = [
  {
    theme: "Deep Sea Discovery",
    template: `# The Abyssal Connection

*Generated by Astroqua AI • ${new Date().toLocaleDateString()}*

---

The depths of the Mariana Trench held secrets that defied explanation. Dr. Elena Vasquez had spent three years preparing for this moment, but nothing could have prepared her for what the submersible's sensors were detecting.

The pressure readings were impossible. At 10,984 meters below the surface, the instruments registered patterns that seemed almost... rhythmic. Like a heartbeat from the very core of the Earth itself.

"Dr. Vasquez, you need to see this," came the voice of her research assistant through the comm system. "The bioluminescent readings are off the charts. It's like the entire ocean floor is... glowing."

Elena adjusted her position in the cramped submersible, her eyes fixed on the holographic displays that surrounded her. The data streams showed something unprecedented: a network of light patterns that extended far beyond what their mapping systems could detect.

As the submersible descended deeper, the water around them began to shimmer with an otherworldly radiance. Tiny particles of light danced in the current, creating constellations that seemed to mirror the star charts Elena had studied during her years at the International Space Station.

The connection was undeniable. The patterns in the deep ocean were identical to the cosmic phenomena she had observed from orbit. But how was this possible?

---

*This is a preview of your AI-generated story. The full narrative would continue based on your selected parameters, exploring the themes of deep sea mystery in a mysterious and atmospheric tone.*`,
  },
  {
    theme: "Cosmic Connection",
    template: `# Stellar Tides

*Generated by Astroqua AI • ${new Date().toLocaleDateString()}*

---

Commander Marcus Chen floated weightlessly in the observation module of the International Space Station, his eyes fixed on the Earth below. The planet's oceans shimmered with patterns that shouldn't exist—currents that moved in perfect synchronization with cosmic phenomena light-years away.

"Mission Control, this is ISS-7," he spoke into his headset, his voice steady despite the growing unease. "We're seeing something... impossible down here."

The data streams from the station's sensors painted a picture that defied all known laws of physics. The ocean currents were responding to gravitational forces that shouldn't affect them. The patterns were too precise, too coordinated to be natural.

Dr. Sarah Kim, the station's astrophysicist, joined him at the observation window. "Marcus, look at this," she said, pointing to her tablet. "The ocean patterns are mirroring the movement of stars in the Andromeda galaxy. But that's... that's not possible."

As they watched, the Earth's oceans began to pulse with a rhythm that seemed to echo across the vastness of space itself. It was as if the planet was breathing, responding to some cosmic heartbeat that connected it to the universe beyond.

The implications were staggering. If the oceans were truly connected to distant galaxies, then everything they thought they knew about the nature of reality was wrong.

---

*This is a preview of your AI-generated story. The full narrative would continue based on your selected parameters, exploring the themes of cosmic connection in a scientific and analytical tone.*`,
  },
  {
    theme: "Bioluminescent Beings",
    template: `# The Light Dancers

*Generated by Astroqua AI • ${new Date().toLocaleDateString()}*

---

The bioluminescent display was unlike anything Dr. Maria Rodriguez had ever witnessed. Deep in the abyssal zone, where sunlight never reached, the creatures of the deep were putting on a performance that seemed almost... intelligent.

Her research submersible hovered silently in the darkness, its cameras capturing every detail of the mesmerizing light show. The creatures—if they could even be called that—moved in perfect synchronization, their bodies pulsing with patterns that seemed to carry meaning.

"Dr. Rodriguez, are you seeing this?" whispered her assistant through the comm system. "The patterns... they're not random. They're communicating."

Maria's heart raced as she realized the truth. These weren't just bioluminescent organisms—they were intelligent beings, and they were trying to communicate with her. The light patterns formed intricate symbols that seemed to tell a story of ancient wisdom and cosmic knowledge.

As she watched, the creatures began to arrange themselves into formations that resembled star charts and mathematical equations. They were showing her something—a message from the depths of time itself.

The implications were profound. If these beings possessed such advanced knowledge, then the ocean depths held secrets that could change everything humanity thought it knew about life, intelligence, and the nature of existence itself.

---

*This is a preview of your AI-generated story. The full narrative would continue based on your selected parameters, exploring the themes of bioluminescent beings in a wonder and discovery tone.*`,
  },
];

export const useAIGeneratorStore = create<AIGeneratorState>()(
  devtools(
    (set, get) => ({
      // Initial state
      theme: "",
      setting: "",
      characters: "",
      conflict: "",
      tone: "",
      length: "",
      isGenerating: false,
      generatedStory: "",
      generationStep: 0,
      generationProgress: 0,
      selectedPreset: null,
      showAdvanced: false,

      // Actions
      setTheme: (theme) => set({ theme }),
      setSetting: (setting) => set({ setting }),
      setCharacters: (characters) => set({ characters }),
      setConflict: (conflict) => set({ conflict }),
      setTone: (tone) => set({ tone }),
      setLength: (length) => set({ length }),
      setGenerating: (isGenerating) => set({ isGenerating }),
      setGeneratedStory: (generatedStory) => set({ generatedStory }),
      setGenerationStep: (generationStep) => set({ generationStep }),
      setGenerationProgress: (generationProgress) => set({ generationProgress }),
      setSelectedPreset: (selectedPreset) => set({ selectedPreset }),
      setShowAdvanced: (showAdvanced) => set({ showAdvanced }),

      resetForm: () =>
        set({
          theme: "",
          setting: "",
          characters: "",
          conflict: "",
          tone: "",
          length: "",
          isGenerating: false,
          generatedStory: "",
          generationStep: 0,
          generationProgress: 0,
          selectedPreset: null,
          showAdvanced: false,
        }),

      generateStory: async () => {
        const state = get();

        set({ isGenerating: true, generationStep: 0, generationProgress: 0 });

        // Simulate AI generation process with realistic steps
        const steps = [
          "Analyzing story parameters...",
          "Connecting to neural networks...",
          "Generating storyline structure...",
          "Crafting character interactions...",
          "Weaving atmospheric details...",
          "Finalizing the narrative...",
        ];

        for (let i = 0; i < steps.length; i++) {
          await new Promise((resolve) => setTimeout(resolve, 800 + Math.random() * 400));
          set({
            generationStep: i + 1,
            generationProgress: Math.round(((i + 1) / steps.length) * 100),
          });
        }

        // Select appropriate template based on theme
        const selectedTemplate =
          mockStoryTemplates.find((t) =>
            state.theme.toLowerCase().includes(t.theme.toLowerCase().split(" ")[0]),
          ) || mockStoryTemplates[0];

        // Customize the story based on user inputs
        let customizedStory = selectedTemplate.template;

        if (state.theme) {
          customizedStory = customizedStory.replace(
            /The Abyssal Connection|Stellar Tides|The Light Dancers/g,
            state.theme,
          );
        }

        if (state.setting) {
          customizedStory = customizedStory.replace(
            /Mariana Trench|International Space Station|abyssal zone/g,
            state.setting,
          );
        }

        if (state.characters) {
          customizedStory = customizedStory.replace(
            /Dr. Elena Vasquez|Commander Marcus Chen|Dr. Maria Rodriguez/g,
            state.characters.split(",")[0] || "Dr. Elena Vasquez",
          );
        }

        set({
          generatedStory: customizedStory,
          isGenerating: false,
          generationStep: steps.length,
          generationProgress: 100,
        });
      },
    }),
    {
      name: "ai-generator-store",
    },
  ),
);
